name: Continuous Integration

on:
  push:
    branches:
      - main
      - 'releases/*'

permissions:
  id-token: write
  contents: read
  attestations: write

jobs:
  test-attest-provenance:
    name: Test attest-provenance action
    runs-on: ubuntu-latest
    permissions:
      attestations: write
      contents: read
      id-token: write

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: run
        id: run 
        run: |
          echo "text" > 1.txt
   
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: '1.txt'


      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: 1.txt
    
      - name: Generate list using Markdown
        run: |
          echo "This is the lead in sentence for the list" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- Lets add a second bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY
